<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="resources/Mr_W/style.css">
    <title>Hospital</title>
</head>
<body>
<div class="head">
    <div class="head-left"><img src="resources/Mr_W/img/hospital2.png"><h1>Hospital QSN System</h1></div>
    <div class="head-right">
        <div>
        <ul>
            <li><a href=""><img src="resources/Mr_W/img/exit2.png">Exit</a></li>
            <li><a href="welcome"><img src="resources/Mr_W/img/home.png">Welcome to the Hospital System</a></li>
        </ul>
        </div>
    </div>
</div>
<div class="container">
    <div class="menu">
        <div class="menu-header"><h2>Menu</h2></div>
        <div class="left_1">
            <a href="registration"><div style="width: 200px"><div style="width: 100px"><img src="resources/Mr_W/img/registration2.png"></div><div class="menu-text">Registration</div></div></a>
        </div>
        <div class="left_1">
            <a href="registrationInformation"><div style="width: 200px"><div style="width: 100px"><img src="resources/Mr_W/img/patient2.png"></div><div class="menu-text">Register Information</div></div></a>
        </div>
        <div class="left_1">
            <a href="payInformation"><div style="width: 200px"><div style="width: 100px"><img src="resources/Mr_W/img/pay2.png"></div><div class="menu-text">Pay Information</div></div></a>
        </div>
    </div>